In [5]:
import torch
x = torch.ones(2, 2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
y = x+2 
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [20]:
z = y * y * 3
out = z.mean()
print(z, out)
print(out)
print(z)

tensor([1367580.1250, 5299586.0000,  145094.5781], grad_fn=<MulBackward0>) tensor(2270753.5000, grad_fn=<MeanBackward1>)
tensor(2270753.5000, grad_fn=<MeanBackward1>)
tensor([1367580.1250, 5299586.0000,  145094.5781], grad_fn=<MulBackward0>)


In [21]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

v = torch.tensor([0.1, 1.0, 0.0001], dtype = torch.float)
y.backward(v)
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([ -28.6159, -907.6460, -634.1979], grad_fn=<MulBackward0>)
False
True


RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.