In [9]:
import torch
import numpy as np
from matplotlib import pyplot as plt
from IPython import display
from torch.autograd import Variable

In [50]:
# keep the random seed 
torch.manual_seed(40)

#  predict y = x ** 2
x = Variable( torch.Tensor([[1.0] , [5.0] , [10.0]]))
y = Variable( torch.Tensor([[2.0], [10.0] , [20.0]]))

epochs = 10
lr = 0.1
#  auto grad
w = Variable(torch.Tensor([0]) , requires_grad = True)
cost = []

for epoch in range(epochs):
    yhat =  x * w
#     loss = torch.mean( 1/2 * (yhat - y) ** 2) 
    loss = (yhat - y).pow(2).sum()
    cost.append(loss.data.numpy() )
#     backward
    loss.backward()
#     update params
    w.data = w.data - lr * w.grad.data
#     
    w.grad.data.zero_()
    print(w.data)
    
print("params: w = ", w)
    


tensor([50.4000])
tensor([-1169.2800])
tensor([28346.9766])
tensor([-685946.4375])
tensor([16599956.])
tensor([-4.0172e+08])
tensor([9.7216e+09])
tensor([-2.3526e+11])
tensor([5.6934e+12])
tensor([-1.3778e+14])
params: w =  tensor([-1.3778e+14], requires_grad=True)


In [55]:
import torch
from torch.autograd import Variable


class MyReLU(torch.autograd.Function):

    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input


dtype = torch.FloatTensor
N, D_in, H, D_out = 64, 1000, 100, 10

x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)

# Create random Tensors for weights, and wrap them in Variables.
w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # To apply our Function, we use Function.apply method. We alias this as 'relu'.
    relu = MyReLU.apply
    y_pred = relu(x.mm(w1)).mm(w2)

    loss = (y_pred - y).pow(2).sum()

    loss.backward()

    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    
print(w1,w2)

tensor([[ 2.1310, -0.7408, -2.1250,  ..., -0.4868,  0.4722, -0.5242],
        [ 2.1613, -0.0093,  0.7943,  ...,  0.3371, -1.3026, -0.9284],
        [ 1.2582,  0.3077, -0.9613,  ...,  0.9164,  0.6530, -0.9015],
        ...,
        [-1.4190,  0.4592,  1.2327,  ...,  0.7093,  0.3147, -0.7833],
        [-0.0497,  1.5008, -0.0748,  ...,  0.7749,  0.1199, -0.3916],
        [ 0.0073, -1.2980,  1.0442,  ...,  0.9261, -0.9148, -1.4677]],
       requires_grad=True) tensor([[-8.8664e-01, -2.5597e-01,  9.3969e-01,  1.1109e+00,  8.4252e-02,
          1.0729e-01,  5.6023e-02,  8.9432e-01,  8.5153e-01,  2.1403e-01],
        [-8.2920e-01, -1.0567e+00,  4.6244e-01,  9.6906e-01, -1.9030e-01,
         -1.6422e-01, -3.2483e-01,  8.8905e-01, -4.5939e-01,  6.9666e-01],
        [ 9.7988e-03,  1.7017e-01, -5.9349e-01, -7.9309e-01, -7.5687e-01,
         -4.4043e-01,  3.1250e-01, -2.2486e-01, -1.2274e+00, -5.7356e-01],
        [-1.9086e-03,  1.3971e+00,  5.5556e-01,  7.8095e-01,  4.4842e-01,
         -1.3410e-

In [61]:
x = torch.randn(3) 
x = Variable(x , requires_grad = True)

y=  x*2
while y.data.norm() < 200:
    y = y*2
    
print(y)
z = y * y * 2
out = z.mean()
out.backward()
print(x.grad)

tensor([230.0903, 213.3511,  68.1772], grad_fn=<MulBackward0>)
tensor([39268.7539, 36411.9297, 11635.5801])
