In [9]:
import torch
import numpy as np
from matplotlib import pyplot as plt
from IPython import display
from torch.autograd import Variable

In [42]:
# keep the random seed 
torch.manual_seed(40)

#  predict y = x ** 2
x = Variable( torch.Tensor([[1.0] , [5.0] , [10.0]]))
y = Variable( torch.Tensor([[2.0], [10.0] , [20.0]]))

epochs = 10
lr = 0.1
#  auto grad
w = Variable(torch.Tensor([0]) , requires_grad = True)
cost = []

for epoch in range(epochs):
    yhat =  x * w
    loss = torch.mean( 1/2 * (yhat - y) ** 2) 
#     convert to numpy  ???
#     print(type())
#     temp = loss.data.numpy()
#     print(temp[0]
#     cost.append(loss.data.from_numpy[0] )
#     backward
    loss.backward()
#     update params
    w.data = w.data - lr * w.grad.data
#     
    w.grad.data.zero_()
    print(w.data)
    
print("params: w = ", w)
    


tensor([8.4000])
tensor([-18.4800])
tensor([67.5360])
tensor([-207.7152])
tensor([673.0887])
tensor([-2145.4844])
tensor([6873.9502])
tensor([-21988.2422])
tensor([70370.7812])
tensor([-225178.0938])
params: w =  tensor([-225178.0938], requires_grad=True)
