In [1]:
import torch
import numpy as np
from matplotlib import pyplot as plt
from IPython import display
from torch.autograd import Variable

In [2]:
# keep the random seed 
torch.manual_seed(40)

#  predict y = x ** 2
x = Variable( torch.Tensor([[1.0] , [5.0] , [10.0]]))
y = Variable( torch.Tensor([[2.0], [10.0] , [20.0]]))

epochs = 10
lr = 0.1
#  auto grad
w = Variable(torch.Tensor([0]) , requires_grad = True)
cost = []

for epoch in range(epochs):
    yhat =  x * w
#     loss = torch.mean( 1/2 * (yhat - y) ** 2) 
    loss = (yhat - y).pow(2).sum()
    cost.append(loss.data.numpy() )
#     backward
    loss.backward()
#     update params
    w.data = w.data - lr * w.grad.data
#     
    w.grad.data.zero_()
    print(w.data)
    
print("params: w = ", w)
    


tensor([50.4000])
tensor([-1169.2800])
tensor([28346.9766])
tensor([-685946.4375])
tensor([16599956.])
tensor([-4.0172e+08])
tensor([9.7216e+09])
tensor([-2.3526e+11])
tensor([5.6934e+12])
tensor([-1.3778e+14])
params: w =  tensor([-1.3778e+14], requires_grad=True)


In [3]:
import torch
from torch.autograd import Variable


class MyReLU(torch.autograd.Function):

    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input.clamp(min=0)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        grad_input = grad_output.clone()
        grad_input[input < 0] = 0
        return grad_input


dtype = torch.FloatTensor
N, D_in, H, D_out = 64, 1000, 100, 10

x = Variable(torch.randn(N, D_in).type(dtype), requires_grad=False)
y = Variable(torch.randn(N, D_out).type(dtype), requires_grad=False)

# Create random Tensors for weights, and wrap them in Variables.
w1 = Variable(torch.randn(D_in, H).type(dtype), requires_grad=True)
w2 = Variable(torch.randn(H, D_out).type(dtype), requires_grad=True)

learning_rate = 1e-6
for t in range(500):
    # To apply our Function, we use Function.apply method. We alias this as 'relu'.
    relu = MyReLU.apply
    y_pred = relu(x.mm(w1)).mm(w2)

    loss = (y_pred - y).pow(2).sum()

    loss.backward()

    w1.data -= learning_rate * w1.grad.data
    w2.data -= learning_rate * w2.grad.data

    w1.grad.data.zero_()
    w2.grad.data.zero_()
    
print(w1,w2)

tensor([[-0.9820,  1.3044,  0.0667,  ..., -0.8037,  0.7924, -1.6305],
        [ 0.0479,  0.6408,  1.3767,  ..., -0.6639, -0.1990, -0.8133],
        [ 0.2227,  0.1973, -0.3813,  ...,  1.6876, -0.7558, -0.6828],
        ...,
        [ 0.4948, -1.0863,  0.4279,  ..., -0.1037,  0.0596,  0.2432],
        [ 1.2823, -0.0737, -1.0106,  ..., -0.1413,  1.6265,  0.4110],
        [-1.4512,  0.1291, -2.6743,  ..., -0.7815,  1.3336,  1.2244]],
       requires_grad=True) tensor([[-1.2735e+00, -8.9793e-01,  6.4133e-01,  7.5476e-01,  3.5676e-01,
          1.3167e-01,  1.6725e-01, -1.2724e-01, -2.3486e-01, -1.2961e-01],
        [ 8.2757e-01, -1.0042e+00,  9.8581e-01, -2.0471e-01, -1.4778e+00,
         -2.6712e-01,  7.2077e-01, -1.1514e-01, -8.4820e-01,  6.2432e-01],
        [ 1.2330e-01, -7.8261e-01,  1.1940e+00,  9.5170e-01,  1.2880e-01,
          1.3210e+00, -2.2987e-01, -1.9767e+00, -5.9122e-01, -8.1349e-01],
        [-1.5243e+00, -4.2206e-01, -1.2975e+00, -1.1548e+00, -6.2001e-01,
          7.5317e-

In [4]:
x = torch.randn(3) 
x = Variable(x , requires_grad = True)

y=  x*2
while y.data.norm() < 200:
    y = y*2
    
print(y)
z = y * y * 2
out = z.mean()
out.backward()
print(x.grad)

tensor([-134.6501,  212.0656,  -67.9910], grad_fn=<MulBackward0>)
tensor([-45960.5859,  72385.0469, -23207.5938])


In [5]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt
