## DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ
### what is PyTorch
#### Tensors

In [3]:
from __future__ import print_function
import torch

In [8]:
# Construct a 5x3 matrix, uninitialized: ???
x = torch.empty(5,3) 
print(x)

tensor([[0.0000e+00, 3.6893e+19, 0.0000e+00],
        [3.6893e+19, 7.0065e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 3.6893e+19, 6.4473e+07]])


Construct a randomly initialized matrix:

In [10]:
x = torch.rand(6,4)
x

tensor([[0.4391, 0.3887, 0.0031, 0.2382],
        [0.0832, 0.6832, 0.2891, 0.2200],
        [0.0527, 0.4320, 0.1430, 0.3232],
        [0.8111, 0.2369, 0.6401, 0.9743],
        [0.4230, 0.2300, 0.9978, 0.0036],
        [0.9032, 0.9622, 0.6629, 0.0880]])

Construct a matrix filled zeros and of dtype long:

In [6]:
x = torch.zeros(5, 3 ,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:
create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, **e.g. dtype, unless new values are provided by user**

In [15]:
x = torch.tensor([5.1,4])
print(x)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([5.1000, 4.0000])
tensor([ 0.8435, -0.6759])


In [20]:
x = x.new_ones(3,4, dtype = torch.double)
print(x,x.size())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) torch.Size([3, 4])


**Addition "+" ** 

In [29]:
y = torch.rand(3, 4, dtype=torch.double )
print(x+y)

print(torch.add(x, y))

print(torch.add(x,y, out = result))
print(result)

tensor([[1.8524, 1.0007, 1.8668, 1.5254],
        [1.5798, 1.2654, 1.8589, 1.9564],
        [1.0217, 1.2825, 1.9320, 1.6098]], dtype=torch.float64)


tensor([[1.8524, 1.0007, 1.8668, 1.5254],
        [1.5798, 1.2654, 1.8589, 1.9564],
        [1.0217, 1.2825, 1.9320, 1.6098]], dtype=torch.float64)

In [28]:
z = torch.tensor([1,2])
z = z.new_ones(2, 4, dtype = torch.long)
print(z)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]])
