## DEEP LEARNING WITH PYTORCH: A 60 MINUTE BLITZ
### what is PyTorch
#### Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized: ???
x = torch.empty(5,3) 
print(x)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 9.3079e-04, 1.7743e+28],
        [1.0918e+18, 1.3032e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(6,4)
x

tensor([[0.4890, 0.1359, 0.3772, 0.0274],
        [0.7642, 0.6477, 0.3606, 0.5396],
        [0.9184, 0.2816, 0.1178, 0.2443],
        [0.8689, 0.8764, 0.9413, 0.1996],
        [0.2205, 0.5871, 0.1635, 0.3762],
        [0.7886, 0.1407, 0.1391, 0.7241]])

Construct a matrix filled zeros and of dtype long:

In [4]:
x = torch.zeros(5, 3 ,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:
create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, **e.g. dtype, unless new values are provided by user**

In [5]:
x = torch.tensor([5.1,4])
print(x)
x = torch.randn_like(x, dtype = torch.float)
print(x)

tensor([5.1000, 4.0000])
tensor([-0.8190, -0.3291])


In [6]:
x = x.new_ones(3,4, dtype = torch.double)
print(x,x.size())

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64) torch.Size([3, 4])


**Addition "+" ** 

In [11]:
y = torch.rand(3, 4, dtype=torch.double )
print(x+y)

print(torch.add(x, y))
result = torch.empty(3,4, dtype = torch.double)
print(torch.add(x,y, out = result))
print(result)

tensor([[1.3422, 1.2544, 1.8863, 1.3379],
        [1.9280, 1.8093, 1.1717, 1.7313],
        [1.9891, 1.1940, 1.4984, 1.6921]], dtype=torch.float64)
tensor([[1.3422, 1.2544, 1.8863, 1.3379],
        [1.9280, 1.8093, 1.1717, 1.7313],
        [1.9891, 1.1940, 1.4984, 1.6921]], dtype=torch.float64)
tensor([[1.3422, 1.2544, 1.8863, 1.3379],
        [1.9280, 1.8093, 1.1717, 1.7313],
        [1.9891, 1.1940, 1.4984, 1.6921]], dtype=torch.float64)
tensor([[1.3422, 1.2544, 1.8863, 1.3379],
        [1.9280, 1.8093, 1.1717, 1.7313],
        [1.9891, 1.1940, 1.4984, 1.6921]], dtype=torch.float64)


In [ ]:
z = torch.tensor([1,2])
z = z.new_ones(2, 4, dtype = torch.long)
print(z)

In [12]:
y.add_(x)

tensor([[1.3422, 1.2544, 1.8863, 1.3379],
        [1.9280, 1.8093, 1.1717, 1.7313],
        [1.9891, 1.1940, 1.4984, 1.6921]], dtype=torch.float64)

In [13]:
print(x[:,1])

tensor([1., 1., 1.], dtype=torch.float64)


In [26]:
x = torch.randn(4,4) 
print(x)
y = x.view(16) 
print(y)
z = x.view(-1, 8)
t = x.view(-1,2)
tt = x.view(8,2)
print(tt)
print(t)
print(z)
print(x.size() , y.size(), z.size()) 

tensor([[-0.2169, -1.1567,  0.4875,  0.3804],
        [-1.1352,  0.2438,  0.3438,  0.9655],
        [-1.2870, -0.7361, -0.9815,  1.3824],
        [-1.4966,  0.1513,  0.7213,  0.1252]])
tensor([-0.2169, -1.1567,  0.4875,  0.3804, -1.1352,  0.2438,  0.3438,  0.9655,
        -1.2870, -0.7361, -0.9815,  1.3824, -1.4966,  0.1513,  0.7213,  0.1252])
tensor([[-0.2169, -1.1567],
        [ 0.4875,  0.3804],
        [-1.1352,  0.2438],
        [ 0.3438,  0.9655],
        [-1.2870, -0.7361],
        [-0.9815,  1.3824],
        [-1.4966,  0.1513],
        [ 0.7213,  0.1252]])
tensor([[-0.2169, -1.1567],
        [ 0.4875,  0.3804],
        [-1.1352,  0.2438],
        [ 0.3438,  0.9655],
        [-1.2870, -0.7361],
        [-0.9815,  1.3824],
        [-1.4966,  0.1513],
        [ 0.7213,  0.1252]])
tensor([[-0.2169, -1.1567,  0.4875,  0.3804, -1.1352,  0.2438,  0.3438,  0.9655],
        [-1.2870, -0.7361, -0.9815,  1.3824, -1.4966,  0.1513,  0.7213,  0.1252]])
torch.Size([4, 4]) torch.Size([16]) tor

In [22]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.4863])
-0.48626407980918884


In [33]:
a = torch.ones(5)
print(a)
print(type(a[0].item()))

tensor([1., 1., 1., 1., 1.])
<class 'float'>


In [34]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [40]:
a = torch.add(a,a)
print(a)

tensor([32., 32., 32., 32., 32.])


### converting numpy array to Torch tensor ; vice versa

In [50]:
import numpy as np
a = np.ones([2,2])
print(a)
b = torch.from_numpy(a)
print(b)

[[1. 1.]
 [1. 1.]]
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [75]:
b = torch.ones(5)
print(b)
c = b.numpy()
print(c)
print(a, b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.] tensor([1., 1., 1., 1., 1.])
